apiVersion: v1
kind: Service
metadata:
  name: k8s-grafana
  namespace: kube-system
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  # type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    name: k8s-grafana
