apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: heapster
  template:
    metadata:
      labels:
        k8s-app: heapster
    spec:
      containers:
      - name: heapster
        image: kubernetes/heapster:canary
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:http://${k8s_master_ip}:8080
        - --sink=influxdb:http://${influxdb_ip}:8086
